version: 2
jobs:
  build:
    working_directory: /root/PSO2
    docker:
      - image: python:3-slim
    steps:
      - run:
          name: Update APT listing
          command: apt-get -qq update
      - run:
          name: Install GIT
          command: apt-get -y install git
      - checkout
      - run:
          name: verifing CSVs
          command: bash ./check.sh
