version: 2
jobs:
  build:
    working_directory: /root/PSO2
    docker:
      - image: python:3-slim
    branches:
      ignore:
        - develop
        - /feature-.*/
        - JP
        - /*_Old/
    steps:
      - run:
          name: Update APT listing
          command: apt-get -qq update
      - run:
          name: Install Git, the fast, scalable, distributed revision control system
          command: apt-get -qq -y install git
      - checkout
      - run:
          name: Install GNU Aspell spell-checker
          command: apt-get -qq -y install aspell-fr
      - run:
          name: Install GNU assembler, linker and binary utilities
          command: apt-get -qq -y install binutils
      - run:
          name: Checking DUP folders
          command: bash ./_sh/dupfolders.sh
      - run:
          name: checking CSV for quote
          command: bash ./_sh/quote.sh
      - run:
          name: verifing CSVs
          command: bash ./_sh/check.sh
      - run:
          name: coverage CSVs
          command: bash ./_sh/coverage.sh>/tmp/coverage.txt
      - run:
          name: spell check CSVs
          command: bash ./_sh/aspell.sh|tee /tmp/spellcheck.txt|tail -n +2|cut -f 2 -d " "|./_sh/sortuniq.sh|tee /tmp/dict.txt
      - store_artifacts:
          path: /tmp/coverage.txt
          destination: coverage.txt
      - store_artifacts:
          path: /tmp/spellcheck.txt
          destination: spellcheck.txt
      - store_artifacts:
          path: /tmp/dict.txt
          destination: dict.txt
