version: 2
jobs:
  build:
    working_directory: /root/PSO2
    docker:
      - image: python:3-slim
    branches:
      ignore:
        - develop
        - /feature-.*/
        - JP
        - /*_Old/
    steps:
      - run:
          name: Update APT listing
          command: apt-get -qq update
      - run:
          name: Install GIT
          command: apt-get -y install git
      - checkout
      - run:
          name: Checking DUP folders
          command: bash ./dupfolders.sh
      - run:
          name: checking CSV for quote
          command: bash ./quote.sh
      - run:
          name: verifing CSVs
          command: bash ./check.sh
      - run:
          name: coverage CSVs
          command: bash ./coverage.sh
